# This script has logic to read the XML data generated by CDA and 
# construct the JSON files used for the D3 Packing and Node-Link View provided by SAV.
import xml
import os
import sys
import xml.etree.ElementTree as ET
import math
import json
import random
import io
from time import gmtime, strftime

dir_path = os.path.dirname(os.path.realpath(__file__))

def CreateContainerJSON(pathToXMLFile):

	print("Calling CreateContainerJSON")

	tree = ET.parse(pathToXMLFile)
	root = tree.getroot()
	context = root.findall("context")[0]
	data = []

	for container in context.findall("container"):	
		packages = container.findall('namespace')
		containerSize = len(packages)
		pArrayData = []
		for package in packages:
			packageSize = len(package.findall('type'))
			packageName = package.get('name')
			pArrayData.append({"id": getRandomPackageName(), "name": packageName, "size": packageSize})
		lastElementIndex = len(container.get('name').split("/")) - 1;
		containerName = container.get('name').split("/")[lastElementIndex]; #CDA usually places the absolute path to the JAR file. Let's only grab the actual name.
		data.append({"id": getRandomContainerName(), "name": containerName, "size": containerSize, "children": pArrayData})

	context = {"name": root.findall('context')[0].get('name'), "children": data}

	with open('PMD_Output.json', 'w') as outfile:
		json.dump(context, outfile)